default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rails_tutorial_development

test:
  <<: *default
  database: rails_tutorial_test

production:
  <<: *default
  database: rails_tutorial_production
